# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.PositiveSmallIntegerField()),
                ('img_url', models.CharField(max_length=256)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField()),
                ('status', models.CharField(max_length=8, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Attendance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Girl'),
        ),
    ]
