# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
