# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('girl_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
